<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Employees.aspx.cs" Inherits="Client.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <main aria-labelledby="title">
        The list of employees...
    </main>
    <div>
        <div>
            <asp:SqlDataSource ID="sqlDataSource1" runat="server"
                ConnectionString="<%$ ConnectionStrings:datWise %>"
                SelectCommand="SELECT EmployeeID, Firstname, Lastname, Email, Phone, HireDate FROM dbo.Employees"
                UpdateCommand="UPDATE dbo.Employees SET Firstname=@Firstname, Lastname=@Lastname, Email=@Email, Phone=@Phone, HireDate=@HireDate WHERE EmployeeID=@EmployeeID"
                DeleteCommand="DELETE FROM dbo.Employees WHERE EmployeeID=@EmployeeID">
                <UpdateParameters>
                    <asp:Parameter Name="Firstname" Type="String" />
                    <asp:Parameter Name="Lastname" Type="String" />
                    <asp:Parameter Name="Email" Type="String" />
                    <asp:Parameter Name="Phone" Type="String" />
                    <asp:Parameter Name="HireDate" Type="DateTime" />
                    <asp:Parameter Name="EmployeeID" Type="Int32" />
                </UpdateParameters>
                <DeleteParameters>
                    <asp:Parameter Name="EmployeeID" Type="Int32" />
                </DeleteParameters>

            </asp:SqlDataSource>

            <asp:GridView ID="GridView1" runat="server" DataSourceID="SqlDataSource1"
                AutoGenerateColumns="false"
                AutoGenerateEditButton="True"
                AutoGenerateDeleteButton="True"
                OnRowEditing="GridView1_RowEditing"
                OnRowUpdating="GridView1_RowUpdating"
                OnRowCancelingEdit="GridView1_RowCancelingEdit"
                OnRowDeleting="GridView1_RowDeleting"
                DataKeyNames="EmployeeID">
                <Columns>
                    <%-- BoundField is used for simple data presentation --%>
                    <asp:BoundField DataField="EmployeeID" HeaderText="Employee ID" ReadOnly="true" SortExpression="EmployeeID" />
                    <asp:TemplateField HeaderText="First Name" SortExpression="Firstname">
                        <ItemTemplate>
                            <%--Here we can use Eval instead of Bind as it's readonly control--%>
                            <asp:Label ID="lblFirstname" runat="server"
                                Text='<%# Eval("Firstname") 
                                %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <%-- This is a data-binding expression, it's used to 2-way binding --%>
                            <asp:TextBox ID="txtFirstname" runat="server"
                                Text='<%# Bind("Firstname")%>'>

                            </asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Last Name" SortExpression="Lastname">
                        <ItemTemplate>
                            <asp:Label ID="lblLastname" runat="server"
                                Text='<%# Eval("Lastname") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtLastname" runat="server"
                                Text='<%# Bind("Lastname")%>'>

                            </asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Email" SortExpression="Email">
                        <ItemTemplate>
                            <asp:Label ID="lblEmail" runat="server"
                                Text='<%# Eval("Email") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtEmail" runat="server"
                                Text='<%# Bind("Email")%>'>

                            </asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Phone" SortExpression="Phone">
                        <ItemTemplate>
                            <asp:Label ID="lblPhone" runat="server"
                                Text='<%# Eval("Phone") %>'></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtPhone" runat="server"
                                Text='<%# Bind("Phone")%>'>

                            </asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>

                    <asp:TemplateField HeaderText="Hire Date" SortExpression="HireDate">
                        <ItemTemplate>
                            <asp:Label ID="lblHireDate" runat="server"
                                Text='<%# Eval("HireDate", "{0:yyyy-MM-dd}") %>'>
                            </asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="txtHireDate" runat="server"
                                Text='<%# Bind("HireDate", "{0:yyyy-MM-dd}") %>'>

                            </asp:TextBox>
                        </EditItemTemplate>
                    </asp:TemplateField>

                </Columns>
            </asp:GridView>
        </div>

    </div>
</asp:Content>
